<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <div class="login">
<form method="get" action="<?= $this->url('computer/create') ?>">
        <p>Username</p>
        <input type="text" name="username">
        <p>Password</p>
        <input type="password" name="password">
        <br/>
        <br/>
        <input type="submit">
</form>
    </div>
</body>
</html>